#!/usr/bin/env bash

if ! command -v bundle &> /dev/null; then
  echo "Error: bundle is not installed." >&2
  exit 1
fi

load_dotenv() {
  set -o allexport
  # shellcheck disable=SC1090
  [[ -f .env ]] && source <(sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g" .env)
  set +o allexport
}

load_dotenv
bundle exec fastlane "$@"
