#!/usr/bin/env bash

if ! command -v bundle &> /dev/null; then
  echo "Error: bundle is not installed." >&2
  exit 1
fi

# Export variables from here to make sure some like JAVA_HOME are set correctly
[[ -f .env ]] && export "$(grep -vE "^(#.*|\s*)$" .env)"

bundle exec fastlane "$@"
