name: 'Fastlane iOS'
description: 'Execute fastlane pipeline for iOS'
inputs:
  build-lane:
    description: 'The build lane that should be executed (values: beta, release)'
    required: true
  enforced-branch:
    description: 'Branch to enforce, recommended (supports regex)'
    required: false
  run-id-as-build:
    description: 'Whether or not to use GitHub build id as build number'
    required: false
    default: 'true'
  commit-increment:
    description: 'Whether or not to commit and push version increment'
    required: false
    default: 'false'
  publish-build:
    description: 'Whether or not to publish build artifacts to the App Store (or TestFlight)'
    required: false
    default: 'true'
  app-identifier:
    description: 'App Store application bundle identifier'
    required: true
  team-id:
    description: 'App Store Connect Team ID (if any)'
    required: false
  itc-team-id:
    description: 'iTunes Connect Team ID (if any)'
    required: false
  scheme:
    description: 'iOS project scheme to build'
    required: true
  configuration:
    description: 'iOS project configuration to use'
    required: false
    default: 'Release'
  xcodeproj:
    description: 'Path to main XCode project'
    required: true
  xcworkspace:
    description: 'Path to main XCode workspace'
    required: false
  apple-key-id:
    description: 'Apple App Store Connect Key ID'
    required: true
  apple-issuer-id:
    description: 'Apple App Store Connect Issuer ID'
    required: true
  apple-key-base64:
    description: 'Apple App Store Connect Key contents (.p8) in base64'
    required: true
  enterprise:
    description: 'Whether or not it is Apple Enterprise'
    required: false
    default: 'false'
  match-password:
    description: 'Password to encrypt/decrypt certificates using match'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true
    - id: create-apple-key-file
      if: ${{ inputs.apple-key-base64 != '' }}
      shell: bash
      run: |
        echo "${{ inputs.apple-key-base64 }}" | base64 -d > __apple_key.p8
        echo "apple-key-file=$(pwd)/__apple_key.p8" >> $GITHUB_OUTPUT
    - id: run-fastlane
      shell: bash
      run: ${{ github.action_path }}/fastlane.sh
      env:
        BUILD_LANE: ${{ inputs.build-lane }}
        RUN_ID_AS_BUILD: ${{ inputs.run-id-as-build }}
        RUN_ID: ${{ github.run_id }}
        MATCH_PASSWORD: ${{ inputs.match-password }}
        FL_ENFORCED_BRANCH: ${{ inputs.enforced-branch }}
        FL_COMMIT_INCREMENT: ${{ inputs.commit-increment }}
        FL_PACKAGE_NAME: ${{ inputs.package-name }}
        FL_APP_IDENTIFIER: ${{ inputs.app-identifier }}
        FL_TEAM_ID: ${{ inputs.team-id }}
        FL_ITC_TEAM_ID: ${{ inputs.itc-team-id }}
        FL_IOS_SCHEME: ${{ inputs.scheme }}
        FL_IOS_CONFIGURATION: ${{ inputs.configuration }}
        FL_XCODE_PROJ: ${{ inputs.xcodeproj }}
        FL_XCODE_WORKSPACE: ${{ inputs.xcworkspace }}
        FL_APPLE_KEY_ID: ${{ inputs.apple-key-id }}
        FL_APPLE_ISSUER_ID: ${{ inputs.apple-issues-id }}
        FL_APPLE_KEY_FILE: ${{ steps.create-apple-key-file.outputs.apple-key-file }}
        FL_APPLE_ENTERPRISE: ${{ inputs.enterprise }}
