name: 'Fastlane Android'
description: 'Execute fastlane pipeline for Android'
inputs:
  build-lane:
    description: 'The build lane that should be executed (values: beta, release)'
    required: true
  java-version:
    description: 'JDK version ([see supported syntax](https://github.com/actions/setup-java#supported-version-syntax))'
    required: false
    default: '17'
  enforced-branch:
    description: 'Branch to enforce, recommended (supports regex)'
    required: false
  run-id-as-build:
    description: 'Whether or not to use GitHub build id as build number'
    required: false
    default: 'true'
  commit-increment:
    description: 'Whether or not to commit and push version increment'
    required: false
    default: 'false'
  publish-build:
    description: 'Whether or not to publish build artifacts to the Play Store'
    required: false
    default: 'true'
  package-name:
    description: 'Android app package name (e.g. com.example.application)'
    required: true
  google-json-key-base64:
    description: 'Google Credentials JSON contents in base64 to upload artifacts (required if publishing is enabled)'
    required: false
  artifact:
    description: 'The type of the artifact that should be produced (values: apk, aab)'
    required: false
    default: 'aab'
  flavor:
    description: 'The build flavor that should be used'
    required: false
  build-type:
    description: 'The build type that should be used'
    required: false
    default: 'Release'
  skip-signing:
    description: 'Whether or not to skip build signing (may not work if `build-type` is Release)'
    required: false
    default: 'false'
  key-store-base64:
    description: 'Android Keystore data contents in base64 (required if signing is enabled)'
    required: false
  key-store-password:
    description: 'Android Keystore password (required if signing is enabled)'
    required: false
  key-alias:
    description: 'Android Keystore key alias (required if signing is enabled)'
    required: false
  key-password:
    description: 'Android Keystore key password (required if signing is enabled)'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true
    - id: create-google-json-file
      if: ${{ inputs.google-json-key-base64 != '' }}
      shell: bash
      run: |
        echo "${{ inputs.google-json-key-base64 }}" | base64 -d > __google_credentials.json
        echo "google-credentials-file=$(pwd)/__google_credentials.json" >> $GITHUB_OUTPUT
    - id: create-keystore-file
      if: ${{ inputs.key-store-base64 != '' }}
      shell: bash
      run: |
        echo "${{ inputs.key-store-base64 }}" | base64 -d > __keystore.jks 
        echo "keystore-file=$(pwd)/__keystore.jks" >> $GITHUB_OUTPUT
    - id: set-env-variables
      shell: bash
      run: ${{ github.action_path }}/fastlane.sh
      env:
        BUILD_LANE: ${{ inputs.build-lane }}
        RUN_ID_AS_BUILD: ${{ inputs.run-id-as-build }}
        RUN_ID: ${{ github.run_id }}
        FL_ENFORCED_BRANCH: ${{ inputs.enforced-branch }}
        FL_COMMIT_INCREMENT: ${{ inputs.commit-increment }}
        FL_PACKAGE_NAME: ${{ inputs.package-name }}
        FL_GOOGLE_JSON_FILE: ${{ steps.create-google-json-file.outputs.google-credentials-file }}
        FL_ANDROID_ARTIFACT: ${{ inputs.artifact }}
        FL_ANDROID_FLAVOR: ${{ inputs.flavor }}
        FL_ANDROID_BUILD_TYPE: ${{ inputs.build-type }}
        FL_ANDROID_SKIP_SIGNING: ${{ inputs.skip-signing }}
        FL_ANDROID_STORE_FILE: ${{ steps.create-keystore-file.outputs.keystore-file }}
        FL_ANDROID_STORE_PASSWORD: ${{ inputs.key-store-password }}
        FL_ANDROID_KEY_ALIAS: ${{ inputs.key-alias }}
        FL_ANDROID_KEY_PASSWORD: ${{ inputs.key-password }}
